function luaString(value) {
  return `"${String(value).replace(/\\/g, "\\\\").replace(/"/g, "\\\"").replace(/[\r\n]/g, " ")}"`;
}

// Set item prices as a Lua table body: ["item key"] = gp, plus ["#id"] = gp when the price has an item id.
function valuesToLua(values, indent) {
  const lines = [];
  for (const value of values ?? []) {
    const gp = Math.max(0, Math.trunc(Number(value.gp) || 0));
    lines.push(`${indent}[${luaString(value.key)}] = ${gp},`);
    if (value.id && value.key !== `#${value.id}`) lines.push(`${indent}[${luaString(`#${value.id}`)}] = ${gp},`);
  }
  return lines;
}

// How each raid core decides loot (see the addon's Modules/Loot.lua).
function lootToLua(loot) {
  if (!loot) return ["GuildedLoot = nil"];
  return [
    "GuildedLoot = {",
    `  default = ${luaString(loot.default)},`,
    // Every EP/GP entry needs a raid core: the addon refuses an award with no core chosen.
    `  coreOnly = ${loot.coreOnly ? "true" : "false"},`,
    `  minimumBid = ${Math.max(0, Math.trunc(loot.minimumBid ?? 10))},`,
    "  values = {",
    ...valuesToLua(loot.values, "    "),
    "  },",
    "  cores = {",
    ...(loot.cores ?? []).flatMap((core) => [
      "    {",
      `      id = ${luaString(core.id)}, name = ${luaString(core.name)}, mode = ${luaString(core.mode)}, pool = ${core.separatePool ? "true" : "false"},`,
      `      reserves = ${Math.max(1, Math.trunc(core.reserves ?? 1))}, baseGp = ${Math.max(0, Math.trunc(core.baseGp ?? 0))},`,
      `      offspec = ${Math.max(0, Math.min(100, Math.trunc(core.offspecPercent ?? 50)))}, minEp = ${Math.max(0, Math.trunc(core.minEp ?? 0))},`,
      "      values = {",
      ...valuesToLua(core.values, "        "),
      "      },",
      "      players = {",
      ...(core.standings ?? []).map((row) => `        { name = ${luaString(row.character)}, ep = ${Math.trunc(row.ep)}, gp = ${Math.trunc(row.gp)}, account = ${luaString(core.accounts?.[row.character] ?? "")} },`),
      "      },",
      // Who is in the core, by in-game character (a backup character is its own row).
      "      roster = {",
      ...(core.roster ?? []).slice(0, 200).map((row) =>
        `        { name = ${luaString(row.name)}, member = ${luaString(row.member)}, role = ${luaString(row.role)}, spot = ${luaString(row.spot)}, backup = ${row.backup ? "true" : "false"} },`),
      "      },",
      "    },"
    ]),
    "  }",
    "}"
  ];
}

export function standingsToLua(data) {
  const rows = data.standings.map((row) =>
    `    { name = ${luaString(row.character)}, ep = ${Math.trunc(row.ep)}, gp = ${Math.trunc(row.gp)}, main = ${row.main ? "true" : "false"}, account = ${luaString(data.accounts?.[row.character] ?? "")} },`
  );
  return [
    "-- Generated by the Guilded companion from the Discord bot. Overwritten",
    "-- automatically; edits here are lost.",
    "GuildedLedgerAccepted = {",
    ...(data.acceptedLedgerRefs ?? []).map((ref) => `  [${luaString(ref)}] = true,`),
    "}",
    "GuildedStandings = {",
    `  updatedAt = ${luaString(data.updatedAt)},`,
    // PR = EP / (GP + baseGp); the addon recomputes PR with this.
    `  baseGp = ${Math.max(0, Math.trunc(data.baseGp ?? 0))},`,
    "  players = {",
    ...rows,
    "  }",
    "}",
    "",
    "-- Dungeon runs the bot has stored; the addon marks these as synced.",
    "GuildedDungeonAccepted = {",
    ...(data.acceptedRunRefs ?? []).map((ref) => `  ${luaString(ref)},`),
    "}",
    "",
    "-- Dungeon points this season (top 10), for the addon's Dungeons tab.",
    ...(data.dungeonBoard ? [
      `GuildedDungeonBoard = { season = ${luaString(data.dungeonBoard.season)}, status = ${luaString(data.dungeonBoard.status ?? "ACTIVE")}, updatedAt = ${luaString(data.updatedAt)}, rows = {`,
      ...data.dungeonBoard.rows.map((row) => `  { name = ${luaString(row.name)}, points = ${Math.trunc(row.points)} },`),
      "}, history = {",
      ...(data.dungeonBoard.history ?? []).map(board => ` { season = ${luaString(board.season)}, status = ${luaString(board.status)}, rows = { ${board.rows.map(row => `{ name = ${luaString(row.name)}, points = ${Math.trunc(row.points)} }`).join(", ")} } },`),
      "} }"
    ] : ["GuildedDungeonBoard = nil"]),
    "",
    "-- Item tooltips: who wishlisted an item and what it usually costs (key = lowercase item name).",
    ...((data.items ?? []).length ? [
      "GuildedItems = {",
      ...data.items.map((item) => `  [${luaString(item.key)}] = { gp = ${item.gp === null || item.gp === undefined ? "nil" : Math.trunc(item.gp)}, n = ${Math.trunc(item.awards ?? 0)}, wn = ${Math.trunc(item.wishTotal ?? 0)}, wish = { ${(item.wish ?? []).map((w) => `{ ${luaString(w.name)}, ${Math.trunc(w.priority)} }`).join(", ")} } },`),
      "}"
    ] : ["GuildedItems = nil"]),
    "",
    "-- Upcoming Discord raids (next three weeks): the addon can make in-game calendar events from them.",
    ...((data.raids ?? []).length ? [
      "GuildedRaids = {",
      ...data.raids.map((raid) => `  { id = ${luaString(raid.id)}, title = ${luaString(raid.title)}, at = ${luaString(raid.at)}, core = ${luaString(raid.core ?? "")}, note = ${luaString(raid.note ?? "")} },`),
      "}"
    ] : ["GuildedRaids = nil"]),
    "",
    "-- How each raid core decides loot: the system, set item prices, own-pool standings.",
    ...lootToLua(data.loot),
    "",
    "-- The next raid's signed-up players (main characters), for /guilded invite raid.",
    ...(data.nextRaid ? [
      `GuildedNextRaid = { id = ${luaString(data.nextRaid.id)}, title = ${luaString(data.nextRaid.title)}, at = ${luaString(data.nextRaid.scheduledAt)}, core = ${luaString(data.nextRaid.core ?? "")}, coreId = ${luaString(data.nextRaid.coreId ?? "")}, players = {`,
      ...data.nextRaid.players.map((player) => `  { name = ${luaString(player.name)}, role = ${luaString(player.role)} },`),
      "}, maybe = {",
      ...(data.nextRaid.maybe ?? []).map((name) => `  ${luaString(name)},`),
      "} }"
    ] : ["GuildedNextRaid = nil"]),
    ""
  ].join("\n");
}

